import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { BasisMeasurement, MeasurementResult } from "../types/simulation";
import { DataRow, EmptyState, Pill, SectionLabel } from "./ui";
import { fmtNum, fmtPct } from "../utils/format";

const BASIS_LABEL: Record<string, string> = {
  Z: "Z Basis (computational)",
  X: "X Basis",
  Y: "Y Basis",
};

function BasisBlock({ m, mismatchThreshold }: { m: BasisMeasurement; mismatchThreshold: number }) {
  const data = [
    { outcome: "0", Expected: Math.round(m.expectedCounts[0]), Observed: m.observedCounts[0] },
    { outcome: "1", Expected: Math.round(m.expectedCounts[1]), Observed: m.observedCounts[1] },
  ];
  const overMismatch = m.mismatch > mismatchThreshold;

  return (
    <div className="rounded-lg border border-base-600/60 bg-base-850/50 p-4">
      <div className="mb-3 flex items-center justify-between">
        <span className="text-[12.5px] font-semibold text-slate-200">{BASIS_LABEL[m.basis]}</span>
        <Pill tone={overMismatch ? "flag" : "legit"}>{fmtPct(m.mismatch)} mismatch</Pill>
      </div>

      <div className="h-40 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={data} margin={{ top: 4, right: 8, left: -18, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.1)" vertical={false} />
            <XAxis dataKey="outcome" tick={{ fill: "#94a3b8", fontSize: 11 }} axisLine={{ stroke: "rgba(148,163,184,0.2)" }} tickLine={false} />
            <YAxis tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} width={40} />
            <Tooltip
              contentStyle={{ background: "#0d1220", border: "1px solid rgba(148,163,184,0.2)", borderRadius: 8, fontSize: 12 }}
              labelStyle={{ color: "#cbd5e1" }}
            />
            <Legend wrapperStyle={{ fontSize: 11, color: "#94a3b8" }} />
            <Bar dataKey="Expected" fill="#a78bfa" radius={[4, 4, 0, 0]} fillOpacity={0.55} />
            <Bar dataKey="Observed" fill="#5eead4" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-3 grid grid-cols-2 gap-x-4">
        <DataRow label="Expected P(0)" value={fmtPct(m.expected.p0)} />
        <DataRow label="Expected P(1)" value={fmtPct(m.expected.p1)} />
        <DataRow label="Observed P(0)" value={fmtPct(m.observedDistribution.p0)} />
        <DataRow label="Observed P(1)" value={fmtPct(m.observedDistribution.p1)} />
        <DataRow label="χ² (basis)" value={fmtNum(m.chiSquare, 3)} />
        <DataRow label="Shots" value={m.shots.toLocaleString()} />
      </div>
    </div>
  );
}

export function MeasurementPanel({
  measurement,
  mismatchThreshold,
}: {
  measurement: MeasurementResult | null;
  mismatchThreshold: number;
}) {
  if (!measurement) {
    return <EmptyState message="No measurement has been run yet. Send a signature from the Client to populate this panel." />;
  }

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 gap-x-6">
        <DataRow label="Requested basis" value={measurement.basis} />
        <DataRow label="Shots / basis" value={measurement.shots.toLocaleString()} />
        <DataRow label="Overall mismatch" value={fmtPct(measurement.overallMismatch)} />
        <DataRow label="Overall χ²" value={fmtNum(measurement.overallChiSquare, 3)} />
      </div>

      <div>
        <SectionLabel>Basis Distributions</SectionLabel>
        <div className="space-y-4">
          {measurement.perBasis.map((m) => (
            <BasisBlock key={m.basis} m={m} mismatchThreshold={mismatchThreshold} />
          ))}
        </div>
      </div>

      <p className="text-[11px] leading-relaxed text-slate-600">
        Observed counts are generated by probabilistic sampling from the effective transmitted distribution
        (which may differ from the expected distribution under an active attack), not hardcoded.
      </p>
    </div>
  );
}
